name: Extension build

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  workflow_dispatch:
  
jobs:
  build:
    runs-on: windows-latest
    env: 
        Configuration: Release
        SolutionPath: src\Unitverse.sln
        VsixManifestPath: src\MappingGenerator.Vsix\source.extension.vsixmanifest
    steps:
    - uses: actions/checkout@v2   
      with:
        fetch-depth: '0'
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - run: |
        ./.github/workflows/AutoVersion.ps1
      shell: pwsh 
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2
    - name: Restore NuGet Packages
      run: nuget restore $env:SolutionPath -Verbosity quiet
    - name: Set version for Visual Studio Extension
      uses: cezarypiatek/VsixVersionAction@1.0
      with:
        version: '${{env.AutoVersion_AssemblySemVer}}'
        vsix-manifest-file: 'src\Unitverse\source.extension.vsixmanifest'
    - name: Build extension
      run: msbuild $env:SolutionPath /t:Rebuild -v:m 
      env: 
        DeployExtension: False
    - name: Test extension
      run: dotnet test --no-build --verbosity minimal $env:SolutionPath
    - name: Collect artifacts - VSIX
      uses: actions/upload-artifact@v2
      with:
        name: Unitverse-VSIX
        path: src\Unitverse\bin\Release\Unitverse.vsix
